# Generated by Django 4.2.14 on 2026-08-03 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('resume_text', models.TextField(verbose_name='Extracted Resume Text')),
                ('job_description', models.TextField(verbose_name='Job Description')),
                ('job_title', models.CharField(blank=True, default='', max_length=200)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('match_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('skills_found', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('keywords_matched', models.JSONField(default=list)),
                ('ai_feedback', models.TextField(blank=True, default='')),
                ('improvement_suggestions', models.JSONField(default=list)),
                ('strengths', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Resume Analysis',
                'verbose_name_plural': 'Resume Analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='analyzer_re_user_id_b75419_idx')],
            },
        ),
    ]
